controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\GameController::index


new:
    path: /new
    controller: App\Controller\GameController::new
